services:

  postgres:
    image: postgres:11.8
    hostname: postgres
    restart: unless-stopped
    stop_grace_period: 20s
    labels:
      group: infra
    command:
      - -c
      - max_connections=1000
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=demo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 10s
      timeout: 10s
      retries: 100
      start_period: 10s