spring:
  application:
    name: task

  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: validate


scheduler:
  enabled: true
  interval: 3600 #seconds
